# Generated by Django 2.1.2 on 2018-10-10 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='albun_logo',
            new_name='album_logo',
        ),
    ]
